name: sealed_class_generator
description: Sealed Class generator parses and generates your sealed classes.
version: 3.1.0
homepage: https://github.com/vrtdev/sealed_class_generator
repository: https://github.com/vrtdev/sealed_class_generator
issue_tracker: https://github.com/vrtdev/sealed_class_generator/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.4.0
  build: ^2.0.0
  source_gen: ^1.0.0
  sealed_class:
    git: 
      url: https://github.com/martirius/sealed_class_generator
      ref: master
      path: ./sealed_class

dev_dependencies:
  build_test: ^2.0.0
  build_runner: ^1.12.2
  test: ^1.16.8

publish_to: none

    
